services:
  - type: web
    name: my-portfolio-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Add your MONGO_URI and any other secrets in the Render dashboard
